.TH "Herbivor" 3 "Thu Mar 3 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Herbivor \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBHewan\fP\&.
.PP
Inherited by \fBJerapah\fP, and \fBKuda\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBpass\fP ()=0"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
