.TH "Hewan" 3 "Thu Mar 3 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Hewan \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMakhluk\fP\&.
.PP
Inherited by \fBHerbivor\fP, and \fBKarnivor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBmove\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBgrouping\fP ()=0"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBArahGerak\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
