.TH "Karnivor" 3 "Thu Mar 3 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Karnivor \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBHewan\fP\&.
.PP
Inherited by \fBSerigala\fP, and \fBSinga\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBfight\fP (\fBKarnivor\fP *K)=0"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
