.TH "Makhluk" 3 "Thu Mar 3 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Makhluk \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBHewan\fP, and \fBTubuhan\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBkill\fP (int _id)=0"
.br
.ti -1c
.RI "virtual void \fBdestruct\fP ()=0"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBPower\fP"
.br
.ti -1c
.RI "int \fBPosisi\fP"
.br
.ti -1c
.RI "int \fBUsia\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
