.TH "Serigala" 3 "Thu Mar 3 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Serigala \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBKarnivor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSerigala\fP (int Power, int Usia, int PosisiAwal, int ArahGerak, int Id)"
.br
.ti -1c
.RI "void \fBKill\fP (int id)"
.br
.ti -1c
.RI "void \fBDestruct\fP ()"
.br
.ti -1c
.RI "void \fBMove\fP ()"
.br
.ti -1c
.RI "void \fBGrouping\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
