.TH "Wortel" 3 "Thu Mar 3 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Wortel \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Tumbuhan\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWortel\fP (int Power, int Usia, int PosisiAwal, int Id)"
.br
.ti -1c
.RI "void \fBKill\fP (int id)"
.br
.ti -1c
.RI "void \fBDestruct\fP ()"
.br
.ti -1c
.RI "void \fBSeed\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
